apiVersion: v1
kind: ServiceAccount
metadata:
  name: component-orchestrator-account
  namespace: oih-dev-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: component-orchestrator-role
  namespace: flows
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: component-orchestrator-rolebinding
  namespace: flows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: component-orchestrator-role
subjects:
  - kind: ServiceAccount
    name: component-orchestrator-account
    namespace: oih-dev-ns
