version: 2.1

aliases:
  - &node_env
    - image: circleci/node:12-stretch
  - &node_mongo_env
    - image: circleci/node:12-stretch
    - image: circleci/mongo:4.4
  - &node_amqp_env
    - image: circleci/node:12-stretch
    - image: rabbitmq:3.8.6-alpine
  - &run_npm_install
    name: Installing Dependencies
    command: yarn --ignore-engines
  - &only_master_filter
    branches:
      only: master
  - &yarn_test_steps
    - restore_cache:
        keys:
          - yarn-deps-{{ .Branch }}-{{ .Revision }}
    - run: yarn test
  - &build_steps
    - setup_remote_docker
    - restore_cache:
        keys:
          - yarn-deps-{{ .Branch }}-{{ .Revision }}
    - run: |
        git diff --no-commit-id --name-only -r `git log -n 2 --oneline --pretty=format:"%h" --first-parent master | tail -n1` > gitchanges.txt
        cd ./scripts # needed for compatible with travis implementation
        node getChanges.js
        node build.js
    - save_cache:
        key: build-deps-{{ .Branch }}-{{ .Revision }}
        paths:
          - ~/oih
  - &deploy_steps
    - restore_cache:
        keys:
          - build-deps-{{ .Branch }}-{{ .Revision }}
    - run: |
        cd ./scripts  # needed for compatible with travis implementation
        node deploy.js
jobs:
  deps:
    docker: *node_env
    working_directory: ~/oih
    steps:
      - checkout:
          path: ~/oih
      - run: *run_npm_install
      - save_cache:
          key: yarn-deps-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/oih
  test:
    docker: *node_env
    steps:
      - run: echo OK
  build:
    docker: *node_env
    working_directory: ~/oih
    steps: *build_steps
  deploy:
    docker: *node_env
    working_directory: ~/oih
    steps: *deploy_steps
  webhooks-test:
    docker: *node_mongo_env
    working_directory: ~/oih/services/webhooks
    steps: *yarn_test_steps
  iam-test:
    docker: *node_env
    working_directory: ~/oih/services/iam
    steps: *yarn_test_steps
  web-ui-test:
    docker: *node_env
    working_directory: ~/oih/services/web-ui
    steps: *yarn_test_steps
  meta-data-repository-test:
    docker: *node_env
    working_directory: ~/oih/services/meta-data-repository
    steps: *yarn_test_steps
  reports-analytics-test:
    docker: *node_env
    working_directory: ~/oih/services/reports-analytics
    steps: *yarn_test_steps
  app-directory-test:
    docker: *node_env
    working_directory: ~/oih/services/app-directory
    steps: *yarn_test_steps
  component-orchestrator-test:
    docker: *node_mongo_env
    working_directory: ~/oih/services/component-orchestrator
    steps: *yarn_test_steps
  scheduler-test:
    docker: *node_mongo_env
    working_directory: ~/oih/services/scheduler
    steps: *yarn_test_steps
  secret-service-lib-test:
    docker: *node_env
    working_directory: ~/oih/lib/secret-service
    steps: *yarn_test_steps
  lib-backend-commons-lib-test:
    docker: *node_env
    working_directory: ~/oih/lib/backend-commons-lib
    steps: *yarn_test_steps
  lib-component-orchestrator-test:
    docker: *node_env
    working_directory: ~/oih/lib/component-orchestrator
    steps: *yarn_test_steps
  lib-scheduler-test:
    docker: *node_env
    working_directory: ~/oih/lib/scheduler
    steps: *yarn_test_steps
  lib-webhooks-test:
    docker: *node_env
    working_directory: ~/oih/lib/webhooks
    steps: *yarn_test_steps
  lib-component-repository-test:
    docker: *node_mongo_env
    working_directory: ~/oih/lib/component-repository
    steps: *yarn_test_steps
  lib-ferryman-test:
    docker: *node_amqp_env
    working_directory: ~/oih/lib/ferryman
    steps: *yarn_test_steps
  flow-repository-test:
    docker: *node_env
    working_directory: ~/oih/services/flow-repository
    steps: *yarn_test_steps
  audit-log-test:
    docker: *node_env
    working_directory: ~/oih/services/audit-log
    steps: *yarn_test_steps
  data-hub-test:
    docker: *node_mongo_env
    working_directory: ~/oih/services/data-hub
    steps: *yarn_test_steps
  ils-test:
    docker: *node_env
    working_directory: ~/oih/services/ils
    steps: *yarn_test_steps
  dispatcher-service-test:
    docker: *node_env
    working_directory: ~/oih/services/dispatcher-service
    steps: *yarn_test_steps
workflows:
  pipeline:
    jobs:
      - deps
      - webhooks-test:
          requires:
            - lib-webhooks-test
      - iam-test:
          requires:
            - deps
      - web-ui-test:
          requires:
            - deps
      - meta-data-repository-test:
          requires:
            - deps
      - reports-analytics-test:
          requires:
            - deps
      - app-directory-test:
          requires:
            - deps
      - component-orchestrator-test:
          requires:
            - lib-component-orchestrator-test
      - scheduler-test:
          requires:
            - lib-scheduler-test
      - secret-service-lib-test:
          requires:
            - deps
      - flow-repository-test:
          requires:
            - deps
      - audit-log-test:
          requires:
            - deps
      - dispatcher-service-test:
          requires:
            - deps
      - lib-backend-commons-lib-test:
          requires:
            - deps
      - lib-ferryman-test:
          requires:
            - deps
      - lib-component-orchestrator-test:
          requires:
            - lib-backend-commons-lib-test
      - lib-scheduler-test:
          requires:
            - lib-backend-commons-lib-test
      - lib-webhooks-test:
          requires:
            - lib-backend-commons-lib-test
      - lib-component-repository-test:
          requires:
            - lib-backend-commons-lib-test
      - data-hub-test:
          requires:
            - lib-backend-commons-lib-test
      - ils-test:
          requires:
            - deps
      - test:
          requires:
            - webhooks-test
            - iam-test
            - web-ui-test
            - meta-data-repository-test
            - reports-analytics-test
            - app-directory-test
            - component-orchestrator-test
            - scheduler-test
            - secret-service-lib-test
            - flow-repository-test
            - audit-log-test
            - lib-component-repository-test
            - lib-ferryman-test
            - data-hub-test
            - ils-test
            - dispatcher-service-test
      - build:
          requires:
            - test
          filters: *only_master_filter
      - deploy:
          requires:
            - build
          filters: *only_master_filter
