apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
spec:
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/localVolume/
