kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-volume-claim
  namespace: oih-dev-ns
  labels:
    app: mongodb
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
