apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oih-prod-ingress
  namespace: oih-dev-ns
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "oih-prod-ingress"
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:911355339532:certificate/43fe18c5-c3a3-416b-b8dd-b3263a32ae17
  labels:
    app: oih-ingress
spec:
  rules:
  - host: oih-iam.odinanswers.com
    http:
      paths:
        - backend:
            serviceName: iam
            servicePort: 3099
  - host: oih-skm.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: secret-service
          servicePort: 3000
  - host: oih-flow-repository.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: flow-repository
          servicePort: 3001
  - host: oih-auditlog.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: audit-log
          servicePort: 3007
  - host: oih-metadata.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: meta-data-repository
          servicePort: 3000
  - host: oih-component-repository.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: component-repository-service
          servicePort: 1234
  - host: oih-webhooks.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: webhooks-service
          servicePort: 1234
  - host: oih-web-ui.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: web-ui
          servicePort: 3000
  - host: oih-attachment-storage-service.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: attachment-storage-service
          servicePort: 3002
  - host: oih-data-hub.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: data-hub-service
          servicePort: 1234
  - host: oih-ils.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: ils
          servicePort: 3003
  - host: oih-dispatcher-service.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: dispatcher-service
          servicePort: 3013
  - host: oih-app-directory.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: app-directory
          servicePort: 3000
  - host: oih-grafana.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
  - host: oih-reports-analytics.odinanswers.com
    http:
      paths:
      - backend:
          serviceName: reports-analytics
          servicePort: 3000
