kind: Deployment
apiVersion: apps/v1
metadata:
  name: data-hub
  namespace: oih-dev-ns
  labels:
    app: data-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-hub
  template:
    metadata:
      name: data-hub
      labels:
        app: data-hub
    spec:
      containers:
        - name: data-hub
          image: 'openintegrationhub/data-hub:latest'
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: data-hub
                  key: MONGODB_URI
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: data-hub
                  key: RABBITMQ_URI
            - name: PORT
              value: '1234'
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: data-hub
                  key: IAM_TOKEN
            - name: LOG_LEVEL
              value: trace
          resources:
            limits:
              cpu: 0.1
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
