kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner
  namespace: oih-dev-ns
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:v0.1.0
          env:
            - name: FILE_SYSTEM_ID
              #value: fs-91719411 # uiupdate
              value: fs-0571bc85 # prod
            - name: AWS_REGION
              value: us-east-1
            - name: PROVISIONER_NAME
              value: eks-course/aws-efs
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            #server: fs-91719411.efs.us-east-1.amazonaws.com # uiupdate
            server: fs-0571bc85.efs.us-east-1.amazonaws.com # prod
            path: /